### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by lechat69** [r-a-y/bbp-live-preview#1]
The preview ramdomly update itself when editing the textarea
The refresh time seams to be long...

**Comment by r-a-y** [comment]
The refresh time is not random; it's set to 1.5 seconds.

The reason why the timeout is that long is every time live preview happens, you are pinging the server for updated contents.  So you shouldn't really ping the server so often.

If you do not like 1.5 seconds and wish to make it smaller, change the number on this line:
https://github.com/r-a-y/bbp-live-preview/blob/master/bbp-live-preview.php#L96

Going to close this one.
