### ISSUE TITLE
Switching between 'Write' and 'Preview'

### ISSUE THREAD

**Issue by ansnap** [r-a-y/bbp-live-preview#5]
Hi @r-a-y 

Here, on github.com, there is the handy switcher between the 'Write' and 'Preview' modes. Don't you plan to apply the same tabs in your plugin? Sometimes it's handier to switch to preview rather than having the ajax loader beneath the textarea.

Thanks.

**Comment by r-a-y** [comment]
I don't plan on adding a switch between "Write" and "Preview" because bbPress already has a tab when the rich-text editor is enabled, so that would complicate the UI.
